npx webpack --mode=production
cp web/main.* ..\bchoi12.github.io\birdtown\
cp web/style* ..\bchoi12.github.io\birdtown\
cp web/index* ..\bchoi12.github.io\birdtown\
cp web/ticker.* ..\bchoi12.github.io\birdtown\
cp web/texture/* ..\bchoi12.github.io\birdtown\texture\
cp web/mesh/* ..\bchoi12.github.io\birdtown\mesh\
cp web/img/* ..\bchoi12.github.io\birdtown\img\
cp web/music/* ..\bchoi12.github.io\birdtown\music\
cp web/sound/* ..\bchoi12.github.io\birdtown\sound\