

export enum StringType {
	UNKNOWN,

	ENTITY_UNKNOWN,
	ENTITY_BAZOOKA,
	ENTITY_GATLING,
	ENTITY_HEADPHONES,
	ENTITY_JETPACK,
	ENTITY_PURPLE_GLOVE,
	ENTITY_PURPLE_HEADBAND,
	ENTITY_RED_GLOVE,
	ENTITY_RED_HEADBAND,
	ENTITY_SCOUTER,
	ENTITY_SNIPER,
}